import "./styles/globals.scss";
import { Source_Sans_3 } from "next/font/google";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const SourceSans = Source_Sans_3({
    subsets: ["latin"],
    weights: ["300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
    return (
        <html className={SourceSans.className} lang="en">
            <body>{children}</body>
        </html>
    );
}
